export const ERROR_CODES = {
  // Client-side errors
  INVALID_INPUT: 'INVALID_INPUT',
  FORM_VALIDATION_ERROR: 'FORM_VALIDATION_ERROR',

  // API errors
  NETWORK_ERROR: 'NETWORK_ERROR',
  API_VALIDATION_ERROR: 'API_VALIDATION_ERROR',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  SERVER_ERROR: 'SERVER_ERROR',

  // Other errors
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
};
