import React from "react";
import Buttons from "./Buttons";

export default function Disclaimer() {
  return (
    <div className="min-h-screen  flex items-center justify-center p-6">
      <div className="max-w-5xl w-full white-background shadow-2xl rounded-2xl border border-gray-200 overflow-hidden animate-fadeIn">
        <header className="flex items-center gap-4 p-6 border-b border-gray-200 bg-gradient-to-r from-[#c3e0e0]  to-[#c3e0e0]">
          <div className="flex-shrink-0">
            <Buttons
              onClick={() => window.history.back()}
              aria-label="Go back"
              className="flex items-center gap-2 px-4 py-2 rounded-lg transition text-sm font-medium   white-text primary-background"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                className="h-4 w-4"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M15 19l-7-7 7-7"
                />
              </svg>
              Back
            </Buttons>
          </div>
          <div className="flex-grow flex justify-center">
            <h1 className="text-xl md:text-2xl font-bold primary-color ml-2 tracking-tight">
              Legal Disclaimer
            </h1>
          </div>
        </header>

        <main className="p-8 md:p-10 text-slate-700 leading-relaxed">
          <div className="prose prose-slate max-w-none">
            <p className="text-lg font-medium text-gray-700">
              Career Mitra provides education and career guidance through
              psychometric assessments, counseling, and related tools. All
              recommendations, reports, and insights generated by our platform
              or our counselors are intended solely for informational and
              guidance purposes.
            </p>

            <ul className="list-disc pl-6 space-y-2 mt-6">
              <li>
                Career Mitra does not guarantee admission, employment, success,
                or outcomes in any specific education program, examination, or
                career path.
              </li>
              <li>
                The final decision regarding the choice of education stream,
                course, institution, or career path rests entirely with the
                student and their parent/guardian.
              </li>
              <li>
                Career Mitra and its team shall not be held liable for any
                academic, professional, financial, or personal consequences
                arising from the use of our services or recommendations.
              </li>
              <li>
                By using our platform or services, you acknowledge that you are
                responsible for your own education and career decisions.
              </li>
            </ul>
          </div>
        </main>
      </div>
    </div>
  );
}
